- hosts: raspberrypi
  become: true
  tasks:
    - name: Update package lists
      apt: update_cache=yes

    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - libssl-dev
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable
        state: present

    - name: Update package lists again
      apt: update_cache=yes

    - name: Install Docker components
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Create Docker group
      group:
        name: docker
        state: present

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install Portainer
      shell: |
        docker volume create portainer_data
        docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
      register: install_portainer
      changed_when: install_portainer.rc == 0

    - name: Install Fail2ban
      apt:
        name: fail2ban
        state: present

    - name: Enable Fail2ban service
      systemd:
        name: fail2ban
        enabled: yes
        state: started

    - name: Download nvm installation script
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh
        dest: /tmp/install-nvm.sh

    - name: Install nvm
      shell: bash /tmp/install-nvm.sh
      args:
        creates: /home/{{ ansible_user }}/.nvm

    - name: Set nvm path in profile
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: 'export NVM_DIR="$HOME/.nvm"'
        state: present

    - name: Source nvm profile
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm'
        state: present

    - name: Reload bash profile
      shell: source /home/{{ ansible_user }}/.bashrc
      args:
        executable: /bin/bash

    - name: Install Node.js 20
      shell: . /home/{{ ansible_user }}/.nvm/nvm.sh && nvm install 20

    - name: Install pm2 globally
      npm:
        name: pm2
        state: present
