- name: Install Zsh
  hosts: all
  become: true
  vars:
    user: "{{ ansible_user_id }}"
  tasks:
    - name: Install ZSH
      ansible.builtin.package:
        name: zsh
        state: present

    - name: Set Zsh as default shell
      ansible.builtin.command: chsh -s $(which zsh) {{ user }}
      become: true

    - name: Set powerline fonts package name
      ansible.builtin.set_fact:
        powerlinefonts: "{{ 'fonts-powerline' if ansible_os_family == 'Debian' else 'powerline-fonts' }}"

    - name: Install Powerline fonts
      ansible.builtin.package:
        state: present
        name: "{{ powerlinefonts }}"

    - name: Install Oh My Zsh
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "/home/{{ user }}/.oh-my-zsh"
        depth: 1
      become: false

    - name: Install zsh-autosuggestions plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        depth: 1
      become: false
