- name: Install Zsh
  hosts: local
  connection: local
  tasks:
    - name: Install ZSH
      become: true
      ansible.builtin.package:
        name: zsh
        state: present

    - name: Override powerline fonts package name for Debian.
      ansible.builtin.set_fact:
        powerlinefonts: fonts-powerline
      when: ansible_os_family == 'Debian'

    - name: Install Powerline fonts
      become: true
      ansible.builtin.package:
        state: present
        name: "{{ powerlinefonts }}"

    - name: Install Oh My Zsh # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: /home/hasan/.oh-my-zsh
        depth: 1

    - name: Install zsh-autosuggestions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: /home/hasan/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        depth: 1

    - name: Change user shell to zsh
      ansible.builtin.user:
        name: hasan
        shell: /bin/zsh
